justicz/go-algorand

cmd/opdoc/opdoc.go
config/consensus.go
data/transactions/logic/Makefile
data/transactions/logic/TEAL_opcodes.md
data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go
data/transactions/logic/doc.go
data/transactions/logic/eval.go
data/transactions/logic/eval_test.go
data/transactions/logic/opcodes.go

* Sketched gtxn with additional parameters
* Parameterized all TEAL tests by version
* Closes https://github.com/algorand/go-algorand-internal/issues/305

Implement TEAL versioning

---

data/transactions/logic/README.md
data/transactions/logic/TEAL_opcodes.md
data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go
data/transactions/logic/doc.go
data/transactions/logic/eval.go
data/transactions/logic/eval_test.go
data/transactions/logic/opcodes.go
data/transactions/logic/opcodes_test.go
data/transactions/logic/txnfield_string.go

* txn and gtxn also support txna/gtxna syntax in assembler
* expose ApplicationArgs and Accounts to TEAL
* remove app_arg
* restore test coverage to 85.5%

Implement txna and gtxna

---

data/basics/teal.go
data/transactions/logic/eval.go
data/transactions/logic/eval_test.go

* Local state read and write operations go through a cache
to reflect updates after write for subsequent read operations

Implement app_write_local

---

cmd/opdoc/opdoc.go
data/transactions/logic/Makefile
data/transactions/logic/README.md
data/transactions/logic/TEAL_opcodes.md
data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go
data/transactions/logic/doc.go
data/transactions/logic/eval.go
data/transactions/logic/eval_test.go
data/transactions/logic/fields.go
data/transactions/logic/fields_string.go
data/transactions/logic/opcodes.go

add TEAL stringops: concat, substring, substring3
add `global LogicSigVersion`
fix bnz

reimplement TEAL string ops: concat, substring, substring3

---

data/transactions/logic/eval.go
data/transactions/logic/evalStateful_test.go
data/transactions/logic/eval_test.go
data/transactions/logic/opcodes.go

* Implement enum field type checking

Implement return type checking

---

cmd/goal/application.go

Fix some documentation in `goal app`.

---

cmd/goal/application.go

Specify that TEAL programs for input are in assembly.

---

data/transactions/logic/eval.go

Fix txn NumAccounts.

---

cmd/goal/application.go

Print hash of approval and clear programs on creation.

---

cmd/goal/application.go

Show size of programs when attempting to create app.

---

cmd/goal/application.go

Add JSON input file format for application calls.

---

test/scripts/e2e_subs/assets-app.sh
test/scripts/e2e_subs/tealprogs/appclear.teal
test/scripts/e2e_subs/tealprogs/appprog.teal

Can we write Assets in Applications? Yes.
E2E test provided.

Write an application to simulate Assets behavior.

---

data/transactions/logic/eval.go

BenchmarkApp shows 3-5% lower time per operation but I think it is measurement error :)

Fix exceed map lookups in local state access in TEAL

---

test/scripts/e2e_subs/assets-app.sh

Prolong timeout for ASA test.

---

data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go
data/transactions/logic/eval_test.go

+ fix failed unit tests (temp fix)

Fix disasm of a single instruction

---

data/transactions/logic/assembler.go
data/transactions/logic/eval.go
data/transactions/logic/evalStateful_test.go
data/transactions/logic/eval_test.go

Closes https://github.com/algorand/go-algorand-internal/issues/357

Replace runtime return type check with test

---

data/transactions/logic/README.md
data/transactions/logic/TEAL_opcodes.md
data/transactions/logic/assembler_test.go
data/transactions/logic/doc.go
data/transactions/logic/eval.go
data/transactions/logic/evalStateful_test.go
data/transactions/logic/eval_test.go
data/transactions/logic/fields.go
data/transactions/logic/fields_string.go
ledger/applications.go

* TODO: implement in AppLedger

Add RoundNumber to global opcode

---

data/basics/msgp_gen.go
data/basics/sort.go
data/basics/teal.go
data/transactions/application.go
data/transactions/logic/eval.go
data/transactions/logic/evalStateful_test.go

This will save space in `ApplyData`.

Convert EvalDeltas to use offset instead of address

---

cmd/tealdbg/cdtState.go
cmd/tealdbg/debugger.go
cmd/tealdbg/local.go
cmd/tealdbg/main.go
cmd/tealdbg/server.go
cmd/tealdbg/util.go
data/transactions/logic/eval.go
data/transactions/logic/evalStateful_test.go

* Implement tealdbg CLI for local and remote debugging
* Bugfixes
* TODO:
1. Support balance records
2. Pass global.Round (and runMode flags) to CDT state
3. Tests

Debugger CLI and fixes

---

data/transactions/logic/eval.go
data/transactions/logic/eval_test.go

Currently, fetching a txn's ID encodes it and hashes it, which is pretty expensive to do. To prevent performance issues in stateful TEAL programs, we should be caching TxIDs after fetching them for the first time.

Cache computed TxIDs in TEAL eval

---

cmd/tealdbg/cdtSession.go
cmd/tealdbg/cdtState.go
cmd/tealdbg/cdtdbg.go
cmd/tealdbg/debugger.go
cmd/tealdbg/local.go
cmd/tealdbg/local_test.go
cmd/tealdbg/main.go
cmd/tealdbg/samples/branch.teal
cmd/tealdbg/server.go
cmd/tealdbg/util.go
cmd/tealdbg/util_test.go
data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go
data/transactions/logic/eval.go

* Allow source-level debugging with
tealdbg debug myprog.teal

CDT: SourceMaps support

---

config/consensus.go
data/transactions/transaction.go

This seems more developer friendly as per some feedback we received.

Only limit total # args and total arg length

---

cmd/goal/application.go

Specifically, do not mention a JSON file if there was none passed in.

Improve error messages for malformed application inputs.

---

cmd/opdoc/opdoc.go
cmd/tealdbg/local.go
cmd/tealdbg/local_test.go
data/transactions/logic/README.md
data/transactions/logic/TEAL_opcodes.md
data/transactions/logic/doc.go
data/transactions/logic/doc_test.go
data/transactions/logic/opcodes.go

TEAL doc update: show changed opcode cost

---

data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go

* base64(ABC//)
* base64 ABC//== //

TEAL: fix line to field parsing

---

cmd/tealdbg/README.md
cmd/tealdbg/cdtSession.go
cmd/tealdbg/cdtState.go
cmd/tealdbg/cdtdbg.go
cmd/tealdbg/debugger.go
cmd/tealdbg/local.go
cmd/tealdbg/localLedger.go
cmd/tealdbg/local_test.go
cmd/tealdbg/main.go
cmd/tealdbg/samples/calls_count.teal
cmd/tealdbg/samples/calls_count_balance.json
cmd/tealdbg/samples/calls_count_txn.json
cmd/tealdbg/server.go
data/transactions/logic/debugger.go

Also some typo fixes and minor code improvements.

Show app states in CDT

---

data/transactions/logic/backwardCompat_test.go
data/transactions/logic/eval.go
data/transactions/logic/eval_test.go
data/transactions/logic/opcodes_test.go

* Remove version check actual opcodes controlled by opsByOpcode array

TEAL tests

---

ledger/applications.go
ledger/applications_test.go

Changes after testing:
* Do not allow zero AppIndex in white list
* Typo in error message

Unit tests for appLedger

---

ledger/eval_test.go

I confirmed that this test would have caught the bug fixed by #103

Add test for `prepareAppEvaluators`

---

config/consensus.go
data/transactions/transaction.go

additionally, replace `MaxApprovalProgramLen` and `MaxClearStateProgramLen` with a single `MaxAppProgramLen`

document app consensus params

---

data/transactions/logic/assembler_test.go
data/transactions/logic/eval.go
data/transactions/logic/evalStateful_test.go
data/transactions/logic/eval_test.go
data/transactions/logic/fields.go
data/transactions/logic/fields_string.go

* Fix exceed copying of app txn fields
* Rename `AssetAssetName` to `AssetName` in `app_asset_params_get`

Add to Asset config and Asset freeze txn fields to TEAL

---

cmd/goal/application.go
cmd/goal/asset.go
cmd/goal/clerk.go
cmd/goal/common.go
cmd/goal/interact.go

* Use outFilename instead of txFilename for writing out

goal: use addTxnFlags where possible

---

cmd/tealdbg/localLedger.go
daemon/algod/api/server/v1/handlers/handlers.go
daemon/algod/api/server/v2/dryrun.go
daemon/algod/api/server/v2/handlers.go
data/transactions/application.go
data/transactions/application_test.go
data/transactions/asset.go
data/transactions/keyreg_test.go
data/transactions/payment_test.go
data/transactions/transaction.go
ledger/applications.go
ledger/applications_test.go
ledger/archival_test.go
ledger/cow.go
ledger/eval.go
ledger/ledger.go

Simplifies the `transactions.Balances` interface

Replace `GetAppCreator` and `GetAssetCreator` with `GetCreator`

---

ledger/accountdb.go

As discussed in https://github.com/algorand/go-algorand/pull/917, it probably makes sense to remove this index unless we end up with a slow query.

Remove `(asset, ctype)` database index on `assetcreators`

---

data/transactions/application.go

I want to bail out earlier if the application does not exist

Ensure we don't check programs if application doesn't exist
